# private data stored in the .env file

services:
  plex:
    # if CPU usage is too high, changed to 'bionic' instead of 'latest'
    # https://github.com/linuxserver/docker-plex/issues/248#issuecomment-733955977
    image: linuxserver/plex:latest
    environment:
      - PUID=${PUID_PLEX}
      - PGID=${PGID_PLEX}
      - UMASK_SET=002
      - VERSION=docker
    volumes:
      - /export/Toshiba/appdata/plex/config:/config
      - /export/Toshiba/ToshibaMedia/Seriale/:/tv
      - /export/Toshiba/ToshibaMedia/Filmy/:/movies
      - /export/Toshiba/ToshibaMedia/Muzyka/:/music
    network_mode: host
    restart: unless-stopped