# private data stored in the .env file

services:
  duckdns:
    image: linuxserver/duckdns:latest
    container_name: duckdns
    # network_mode: host # needed for ipv6
    environment:
      - PUID=${PUID_piotr} #optional
      - PGID=${PGID_users} #optional
      - TZ=Europe/Warsaw
      - SUBDOMAINS=${duckdns_subdomains}
      - TOKEN=${duckdns_token}
      # - UPDATE_IP=ipv6 #both
      - LOG_FILE=false #optional
    # labels:
    #   com.centurylinklabs.watchtower.enable: "true" # update with Watchtower
    restart: unless-stopped
  mariadb:
    image: linuxserver/mariadb:latest
    container_name: nextclouddb
    environment:
      - PUID=${PUID_piotr}
      - PGID=${PGID_users}
      - MYSQL_ROOT_PASSWORD=${mysql_root_password}
      - TZ=Europe/Warsaw
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=${mysql_user}
      - MYSQL_PASSWORD=${mysql_password}
    volumes:
      - /mnt/RAID5/appdata/Nextcloud/database:/config
    ports:
      - 3306:3306 #external:internal
    labels:
      com.centurylinklabs.watchtower.enable: "true" # update with Watchtower
    restart: unless-stopped
  nextcloud:
    # image: lscr.io/linuxserver/nextcloud:latest
    image: registry.gitlab.com/linuxserver.io/docker-nextcloud/nextcloud:30.0.11-previous
    container_name: nextcloud
    environment:
      # - PUID=1000 # ${PUID_piotr}
      - PUID=${PUID_piotr}
      - PGID=${PGID_users}
      - TZ=Europe/Warsaw
    volumes:
      - /mnt/RAID5/appdata/Nextcloud/config:/config
      - /mnt/RAID5/appdata/Nextcloud/data:/data
    depends_on:
      - mariadb
    ports:
      - 446:443 #external:internal, used to be 445:443
      - 82:80 #external:internal
    labels:
      com.centurylinklabs.watchtower.enable: "true" # update with Watchtower
    restart: unless-stopped
  swag: # previously 'letsencrypt'
    image: lscr.io/linuxserver/swag:latest
    container_name: swag
    cap_add:
      - NET_ADMIN
    environment:
      - STAGING=false #change to false after done testing
      - PUID=${PUID_piotr} #change PUID if needed
      - PGID=${PGID_users}  #change PGID if needed
      - TZ=Europe/Warsaw # change Time Zone if needed
      - URL=${letsencrypt_url} #insert your domain name - yourdomain.url
      - SUBDOMAINS=www,nextcloud,qbittorrent
      - VALIDATION=http
      - EMAIL=${email} # define email; required to renew certificate
    volumes:
      - /mnt/RAID5/appdata/letsencrypt:/config  #/srv/dev-disk-by-label-disk1 needs to be adjusted
    ports:
      - 443:443 #external:internal
      - 80:80 #external:internal
    # labels:
    #   com.centurylinklabs.watchtower.enable: "true" # update with Watchtower
    restart: unless-stopped
  plex:
    # if CPU usage is too high, changed to 'bionic' instead of 'latest'
    # https://github.com/linuxserver/docker-plex/issues/248#issuecomment-733955977
    image: linuxserver/plex:latest
    container_name: plex
    environment:
      - PUID=${PUID_piotr}
      - PGID=${PGID_users}
      - UMASK_SET=002
      - VERSION=docker
    volumes:
      - /mnt/RAID5/appdata/plex/:/config
      - /mnt/RAID5/read-write-share/Seriale/:/tv
      - /mnt/RAID5/read-write-share/Filmy/:/movies
      - /mnt/RAID5/read-write-share/Muzyka/:/music
    network_mode: host
    restart: unless-stopped
  pihole:
    image: pihole/pihole:2025.05.0
    ports: # (external:internal/protocol)
      # DNS Ports
      - "53:53/tcp"
      - "53:53/udp"
      # Default HTTP Port
      - "8080:80/tcp"
      # Default HTTPs Port. FTL will generate a self-signed certificate
      - "8443:443/tcp"
      # Uncomment the line below if you are using Pi-hole as your DHCP server
      #- "67:67/udp"
      # Uncomment the line below if you are using Pi-hole as your NTP server
      #- "123:123/udp"
    environment:
      TZ: Europe/Warsaw
      FTLCONF_webserver_api_password: ${pihole_webpassword}
      FTLCONF_dns_upstreams: 1.1.1.1;1.0.0.1;9.9.9.9;149.112.112.112
      FTLCONF_dns_listeningMode: all
    volumes:
      - /mnt/RAID5/appdata/pihole/etc-pihole/:/etc/pihole/
      - /mnt/RAID5/appdata/pihole/etc-dnsmasq.d/:/etc/dnsmasq.d/
    # labels:
    #   com.centurylinklabs.watchtower.enable: "false" # update with Watchtower
    restart: unless-stopped
  syncthing:
    image: lscr.io/linuxserver/syncthing:latest
    container_name: syncthing
    # hostname: syncthing #optional
    environment:
      - PUID=${PUID_piotr}
      - PGID=${PGID_users}
      - TZ=Europe/Warsaw
    volumes:
      - /mnt/RAID5/appdata/syncthing:/config
      - /mnt/RAID5/read-write-share/SyncthingData/:/data1
      # - /path/to/data2:/data2
    ports:
      - 8384:8384
      - 22000:22000/tcp
      - 22000:22000/udp
      - 21027:21027/udp
    restart: unless-stopped
